//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Word
    {
        public byte[] SaltedHash { get; set; }
        public byte[] EncryptedValue { get; set; }
        public int Count { get; set; }
    }
}
